// create queries
const CREATE_BARBER_IN_DB = `
  INSERT
  INTO BARBERS (FIRST_NAME, LAST_NAME, SHOP, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP_CODE, EMAIL, PASSWORD, PUBLIC_ID) 
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`;

// fetch queries
const FETCH_BARBERS_BY_CITY_STATE = `
  SELECT BARBER_ID, CONCAT(FIRST_NAME, ' ', LAST_NAME) AS NAME, ALIAS, SHOP, PUBLIC_ID
  FROM BARBERS
  WHERE CITY = ? AND STATE = ?;
`;
const FETCH_BARBER_BY_EMAIL = `
  SELECT * 
  FROM BARBERS 
  WHERE EMAIL = ?
`;
const FETCH_BARBER_DETAILS_BY_BARBER_ID = `
  SELECT BARBER_ID, PROFILE_IMAGE, FIRST_NAME, LAST_NAME, ALIAS,  SHOP, BIO, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP_CODE, EMAIL, PUBLIC_ID
  FROM BARBERS
  WHERE BARBER_ID = ?
`;
const FETCH_BARBER_DETAILS_BY_PUBLIC_ID = `
  SELECT BARBER_ID, PROFILE_IMAGE, FIRST_NAME, LAST_NAME, ALIAS, SHOP, BIO, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, ZIP_CODE, EMAIL, PUBLIC_ID
  FROM BARBERS
  WHERE PUBLIC_ID = ?
`;

// update queries
const UPDATE_BARBER_DETAILS = `
  UPDATE BARBERS
  SET FIRST_NAME = ?, LAST_NAME = ?, ALIAS = ?, SHOP = ?, BIO = ?, ADDRESS_LINE_1 = ?, ADDRESS_LINE_2 = ?, CITY = ?, STATE = ?, ZIP_CODE = ?
  WHERE BARBER_ID = ?
`;

module.exports = {
  FETCH_BARBERS_BY_CITY_STATE,
  FETCH_BARBER_BY_EMAIL,
  FETCH_BARBER_DETAILS_BY_PUBLIC_ID,
  FETCH_BARBER_DETAILS_BY_BARBER_ID,
  CREATE_BARBER_IN_DB,
  UPDATE_BARBER_DETAILS,
};
