// create queries
const CREATE_SERVICE = `
  INSERT 
  INTO SERVICES (NAME, HOURS, MINUTES, DESCRIPTION, PRICE, BARBER_ID)
  VALUES (?, ?, ?, ?, ?, ?)
`;

// fetch queries
const FETCH_SERVICES_BY_BARBER_ID = `
  SELECT * 
  FROM SERVICES 
  WHERE BARBER_ID = ?
`;
const FETCH_SERVICE_BY_SERVICE_ID_AND_BARBER_ID = `
  SELECT * 
  FROM SERVICES 
  WHERE SERVICE_ID = ? AND BARBER_ID = ?
`;
const FETCH_SERVICE_COUNT_BY_BARBER_ID = `
  SELECT COUNT(*) AS SERVICE_COUNT 
  FROM SERVICES 
  WHERE BARBER_ID = ?
`;

// update queries
const UPDATE_SERVICE = `
  UPDATE SERVICES
  SET NAME = ?, HOURS = ?, MINUTES = ?, DESCRIPTION = ?, PRICE = ?
  WHERE SERVICE_ID = ? AND BARBER_ID = ?
`;

// delete queries
const DELETE_SERVICE_BY_SERVICE_ID_AND_BARBER_ID = `
  DELETE 
  FROM SERVICES 
  WHERE SERVICE_ID = ? AND BARBER_ID = ?
`;

module.exports = {
  CREATE_SERVICE,
  FETCH_SERVICES_BY_BARBER_ID,
  FETCH_SERVICE_BY_SERVICE_ID_AND_BARBER_ID,
  FETCH_SERVICE_COUNT_BY_BARBER_ID,
  UPDATE_SERVICE,
  DELETE_SERVICE_BY_SERVICE_ID_AND_BARBER_ID,
};
