// fetch queries
const FETCH_APPOINTMENTS_BY_CLIENT_EMAIL = `
  SELECT 
    APPOINTMENTS.APPOINTMENT_ID,
    APPOINTMENTS.START_TIME,
    APPOINTMENTS.END_TIME,
    APPOINTMENTS.SERVICES,
    APPOINTMENTS.STATUS,
    CONCAT(BARBERS.FIRST_NAME, ' ', BARBERS.LAST_NAME) AS BARBER_NAME,
    BARBERS.ALIAS AS BARBER_ALIAS,
    BARBERS.SHOP,
    BARBERS.ADDRESS_LINE_1,
    BARBERS.ADDRESS_LINE_2,
    BARBERS.CITY,
    BARBERS.STATE,
    BARBERS.ZIP_CODE,
    BARBERS.EMAIL,
    BARBERS.PUBLIC_ID AS BARBER_PUBLIC_ID
  FROM APPOINTMENTS
    INNER JOIN BARBERS ON BARBERS.BARBER_ID = APPOINTMENTS.BARBER_ID
    INNER JOIN CLIENTS ON CLIENTS.CLIENT_ID = APPOINTMENTS.CLIENT_ID
  WHERE CLIENTS.EMAIL = ?
`;

module.exports = {
  FETCH_APPOINTMENTS_BY_CLIENT_EMAIL,
};
