// create queries
const CREATE_APPOINTMENT = `
  INSERT 
  INTO APPOINTMENTS (CLIENT_ID, BARBER_ID, START_TIME, END_TIME, SERVICES) 
  VALUES (?, ?, ?, ?, ?)
`;

// fetch queries
const FETCH_APPOINTMENTS_BY_EMAIL = `
  SELECT 
    APPOINTMENTS.APPOINTMENT_ID,
    APPOINTMENTS.START_TIME,
    APPOINTMENTS.END_TIME,
    APPOINTMENTS.SERVICES,
    APPOINTMENTS.STATUS,
    CONCAT(BARBERS.FIRST_NAME, ' ', BARBERS.LAST_NAME) AS BARBER_NAME,
    BARBERS.ALIAS AS BARBER_ALIAS,
    BARBERS.SHOP,
    BARBERS.ADDRESS_LINE_1,
    BARBERS.ADDRESS_LINE_2,
    BARBERS.CITY,
    BARBERS.STATE,
    BARBERS.ZIP_CODE,
    BARBERS.EMAIL,
    BARBERS.PUBLIC_ID AS BARBER_PUBLIC_ID,
    BARBERS.PROFILE_IMAGE,
    CONCAT(CLIENTS.FIRST_NAME, ' ', CLIENTS.LAST_NAME) AS CLIENT_NAME,
    CLIENTS.EMAIL AS CLIENT_EMAIL
  FROM APPOINTMENTS
    INNER JOIN BARBERS ON BARBERS.BARBER_ID = APPOINTMENTS.BARBER_ID
    INNER JOIN CLIENTS ON CLIENTS.CLIENT_ID = APPOINTMENTS.CLIENT_ID
  WHERE CLIENTS.EMAIL = ? OR BARBERS.EMAIL = ?
`;

module.exports = {
  CREATE_APPOINTMENT,
  FETCH_APPOINTMENTS_BY_EMAIL,
};
