const FETCH_BARBERS_BY_CITY_STATE = `SELECT * FROM BARBERS WHERE CITY = ? AND STATE = ?`;
const FETCH_IMAGES_BY_BARBER_ID = `SELECT IMAGE_ID, URL FROM BARBER_IMAGES WHERE BARBER_ID = ?`;
const FETCH_REVIEWS_BY_BARBER_ID = `SELECT REVIEWS.REVIEW_ID, REVIEWS.RATING, REVIEWS.DESCRIPTION, REVIEWS.DATE_CREATED, CONCAT(CLIENTS.FIRST_NAME, ' ', CLIENTS.LAST_NAME) as AUTHOR FROM REVIEWS INNER JOIN CLIENTS ON CLIENTS.CLIENT_ID = REVIEWS.CLIENT_ID WHERE BARBER_ID = ?`;
const FETCH_ALL_BARBER_CITY_STATES = `SELECT * FROM BARBER_CITY_STATES`;
const FETCH_CLIENT_BY_EMAIL = `SELECT * FROM CLIENTS WHERE EMAIL = ?`;
const FETCH_BARBER_BY_EMAIL = `SELECT * FROM BARBERS WHERE EMAIL = ?`;

const FETCH_APPOINTMENTS_BY_CLIENT_EMAIL = `SELECT * FROM APPOINTMENTS WHERE CLIENT_ID = (SELECT CLIENT_ID FROM CLIENTS WHERE EMAIL = ?)`;

const CREATE_CLIENT_IN_DB = `INSERT INTO CLIENTS (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, PASSWORD) VALUES (?, ?, ?, ?, ?)`;

module.exports = {
  FETCH_BARBERS_BY_CITY_STATE,
  FETCH_IMAGES_BY_BARBER_ID,
  FETCH_REVIEWS_BY_BARBER_ID,
  FETCH_ALL_BARBER_CITY_STATES,
  FETCH_CLIENT_BY_EMAIL,
  FETCH_BARBER_BY_EMAIL,
  CREATE_CLIENT_IN_DB,
};

/*

SELECT 
APPOINTMENTS.APPOINTMENT_ID,
APPOINTMENTS.SCHEDULED_TIME,
APPOINTMENTS.SERVICES,
APPOINTMENTS.STATUS,
CONCAT(BARBERS.FIRST_NAME, ' ', BARBERS.LAST_NAME) AS BARBER_NAME,
BARBERS.ALIAS AS BARBER_ALIAS,
BARBERS.SHOP AS BARBER_SHOP_NAME,
BARBERS.ADDRESS_LINE_1,
BARBERS.ADDRESS_LINE_2,
BARBERS.
FROM APPOINTMENTS
INNER JOIN BARBERS ON BARBERS.BARBER_ID = APPOINTMENTS.BARBER_ID
INNER JOIN CLIENTS ON CLIENTS.CLIENT_ID = APPOINTMENTS.CLIENT_ID
WHERE CLIENTS.EMAIL = "john.doe@example.com";

*/
